config/routes.rb
Rails.application.routes.draw do
  devise_for :users

  resources :carts, only: [:show] do
    collection do
      get 'add_to'
      post 'remove_from'
      post 'remove_multiple_from'
    end
  end
  resources :products

  root to: 'pages#home'
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/cart.rb
# frozen_string_literal: true

##
# This Plain Ruby Object handles the serialization of the shopping cart object.
# As the user adds and removes products, the cart_controller will update this object.
class Cart

  def initialize(json: nil)
    # Products will be stored as a hash, where the product id will be the
    # key and the quantity in the cart will be the value.
    @cart_contents = if json.blank?
                      {}
                     else
                       JSON.parse(json)
                     end
  end

  def add(product_id:)
    # Initialize the count to zero if the product is not already in the cart
    @cart_contents[product_id.to_s] ||= 0

    # Increase the quantity of the product in the cart
    @cart_contents[product_id.to_s] += 1
  end

  def remove(product_id:)
    @cart_contents.delete(product_id.to_s)
  end

  def contains?(product_id:)
    @cart_contents.include?(product_id.to_s)
  end

  def to_json(opts = nil)
    @cart_contents.to_json(opts)
  end

  def cart_contents
    @cart_contents.keys
  end

end

app/models/product.rb
class Product < ApplicationRecord

  CATEGORIES = %w(otc prescription restricted)

  validates :name, presence: true, length: { maximum: 255 }
  validates :description, presence: true
  validates :category,
    presence: true,
    inclusion: {
      in: CATEGORIES,
      message: "%{value} is not a valid category"
    }

    scope :published, -> { where published: true }
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  # Users are by default visitors, which is set by the database
  enum role: { visitor: 0, admin: 1 }

  # Thanks to Rails magic, this enum creates the methods
  # visitor?, and admin? which return true/false
  # depending on the type of user. A visitor that has a valid
  # vet registration number is a veterinarian?, defined here:

  def veterinarian?
    visitor? && vet_registration_number.present?
  end

  validates(
    :vet_registration_number,
    allow_nil: true,
    allow_blank: true,
    uniqueness: true,
    format: {
      with: /\AVR\d{4,}\z/,
      message: 'must be a valid state Doctor identifier'
    }
  )

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  include Pundit
  after_action :verify_authorized, except: :index, unless: :devise_controller?
  after_action :verify_policy_scoped, only: :index, unless: :devise_controller?

  before_action :configure_permitted_parameters, if: :devise_controller?

  before_action :load_cart

   def load_cart
     @cart = Cart.new(json: session['cart'])
   end

   def save_cart
     session['cart'] = @cart.to_json
   end

   protected

   def configure_permitted_parameters
     devise_parameter_sanitizer.permit(:sign_up, keys: [:vet_registration_number])
   end
end

app/controllers/carts_controller.rb
class CartsController < ApplicationController

  def show
  end

  def add_to
    if params[:product_id].present?
      @cart.add(product_id: params[:product_id])
      save_cart
      redirect_to(product_path(params[:product_id]), only_path: true)
      return
    end
    redirect_to cart_path(@cart)
  end

  def remove_from
    if params[:product_id].present?
      @cart.add(product_id: params[:product_id])
      save_cart
      redirect_to(product_path(params[:product_id]), only_path: true)
      return
    end
    redirect_to(product_paths, only_path: true)
  end

  def remove_multiple_from
    remove_ids = params[:select_products].blank? ? [] : params[:select_products]
    remove_ids.each { |id| @cart.remove(product_id: id) }
    save_cart
    redirect_to cart_path(@cart)
  end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def home
    authorize(self)
  end
end

app/controllers/products_controller.rb
class ProductsController < ApplicationController
  before_action :set_product, only: [:show, :edit, :update, :destroy]

  # GET /products
  # GET /products.json
  def index
    @products = policy_scope(Product)
  end

  # GET /products/1
  # GET /products/1.json
  def show
  end

  # GET /products/new
  def new
    @product = Product.new
    authorize @product
  end

  # GET /products/1/edit
  def edit
  end

  # POST /products
  # POST /products.json
  def create
    @product = Product.new(product_params)

    respond_to do |format|
      if @product.save
        format.html { redirect_to @product, notice: 'Product was successfully created.' }
        format.json { render :show, status: :created, location: @product }
      else
        format.html { render :new }
        format.json { render json: @product.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /products/1
  # PATCH/PUT /products/1.json
  def update
    respond_to do |format|
      if @product.update(product_params)
        format.html { redirect_to @product, notice: 'Product was successfully updated.' }
        format.json { render :show, status: :ok, location: @product }
      else
        format.html { render :edit }
        format.json { render json: @product.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /products/1
  # DELETE /products/1.json
  def destroy
    @product.destroy
    respond_to do |format|
      format.html { redirect_to products_url, notice: 'Product was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_product
      @product = Product.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def product_params
      params.require(:product).permit(:name, :description, :published, :category)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/page_helper.rb
module PageHelper
end

app/helpers/products_helper.rb
module ProductsHelper
end

app/views/carts/show.html.erb
<h1>Your Cart's Products</h1>

<%= form_tag remove_multiple_from_carts_path, method: 'post' do %>
  <table>
    <thead>
      <tr>
        <th>Product Name</th>
        <th>Remove</th>
      </tr>
    </thead>
    <tbody>
      <% @cart.cart_contents.each do |product_id| %>
        <tr>
          <td><%= Product.find_by(id: product_id)&.name %></td>
          <td><%= check_box_tag("select_products[]", product_id ) %></td>
        </tr>
      <% end %>
    </tbody>
  </table>
  <p>
    <%= submit_tag "Remove from Cart" %>
  </p>

<% end %>

<br>
<%= link_to 'Product Index', products_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Acme2</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <p class="notice"><%= notice %></p>
    <p class="alert"><%= alert %></p>
    <%= yield %>
    <footer>
       <% unless user_signed_in? %>
         <%= link_to 'Sign in', new_user_session_path %>
         or
         <%= link_to 'Sign up for a New Account', new_user_registration_path %>
       <% else %>
         <%= link_to('Logout', destroy_user_session_path, method: :delete) %>
       <% end %>
     </footer>
  </body>
</html>

app/views/pages/home.html.erb
<h1>Welcome to ACME® Barn Yard Veterinary Healthcare</h1>
<p>
  <%= link_to("Choose from #{pluralize(Product.count, 'product')}", products_path) %>
</p>

app/views/products/_form.html.erb
<%= form_with(model: product, local: true) do |form| %>
  <% if product.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(product.errors.count, "error") %> prohibited this product from being saved:</h2>

      <ul>
        <% product.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :name %>
    <%= form.text_field :name %>
  </div>

  <div class="field">
    <%= form.label :description %>
    <%= form.text_area :description %>
  </div>

  <div class="field">
    <%= form.label :published %>
    <%= form.check_box :published %>
  </div>

  <div class="field">
    <%= form.label :category %>
    <%= form.label :category, "Over the Counter", value: 'otc'  %>
    <%= form.radio_button :category, 'otc' %>
    <%= form.label :category, "Prescription", value: 'prescription'  %>
    <%= form.radio_button :category, 'prescription' %>
    <%= form.label :category, "Restricted", value: 'restricted'  %>
    <%= form.radio_button :category, 'restricted' %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/products/edit.html.erb
<h1>Editing Product</h1>

<%= render 'form', product: @product %>

<%= link_to 'Show', @product %> |
<%= link_to 'Back', products_path %>

app/views/products/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Products</h1>
<br>
<% if current_user&.admin? %>
  <%= link_to 'New Product', new_product_path %>
  <br>
<% end %>
<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Description</th>
      <th>Published</th>
      <th>Category</th>
      <th>&nbsp;</th>
      <th>&nbsp;</th>
      <th>&nbsp;</th>
    </tr>
  </thead>

  <tbody>
    <% @products.each do |product| %>
      <tr>
        <td><%= product.name %></td>
        <td><%= product.description %></td>
        <td><%= product.published %></td>
        <td><%= product.category %></td>
        <td><%= link_to 'Show', product %></td>
        <td>
          <% if current_user&.admin? %>
            <%= link_to 'Edit', edit_product_path(product) %>
          <% end %>
        </td>
        <td>
          <% if current_user&.admin? %>
            <%= link_to 'Destroy', product, method: :delete, data: { confirm: 'Are you sure?' } %>
          <% end %>
        </td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<% if current_user&.admin? %>
  <%= link_to 'New Product', new_product_path %>
<% end %>

app/views/products/new.html.erb
<h1>New Product</h1>

<%= render 'form', product: @product %>

<%= link_to 'Back', products_path %>

app/views/products/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @product.name %>
</p>

<p>
  <strong>Description:</strong>
  <%= @product.description %>
</p>

<p>
  <strong>Published:</strong>
  <%= @product.published %>
</p>

<p>
  <strong>Category:</strong>
  <%= @product.category %>
</p>

<%= link_to 'Edit', edit_product_path(@product) %> |
<%= link_to 'Back', products_path %>
<% if @cart&.contains?(product_id: @product.id) %>
  <%= link_to 'Remove from Cart', remove_from_carts_path(product_id: @product.id) if @product.published %>
<% else %>
  <%= link_to 'Add to Cart', add_to_carts_path(product_id: @product.id) if @product.published %>
<% end %>